Check explicitly if the TRJ_HOME variable has been set yet.

diff --git a/bin/clean b/bin/clean
--- a/bin/clean
+++ b/bin/clean
@@ -1,7 +1,24 @@
 #!/bin/bash
 
+
+# Check if TRJ_HOME is not set.
+if [ -z $TRJ_HOME ]; then
+  # Notify user that TRJ_HOME is not set.
+  echo "Environment variable TRJ_HOME not found."
+  echo "Please configure the environment variable TRJ_HOME."
+  exit 1
+fi
+
+
+# Relocate into the TRJ_HOME just to be sure.
+cd $TRJ_HOME
+
+
+# Clean compiled java code.
 mvn clean
 
+
+# Clean compiled Python code.
 rm -r src/main/python/trajectory/__pycache__
 rm src/main/python/trajectory/*.pyc
 
diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,15 +1,21 @@
 #!/bin/bash
 
+
 # Halt on error.
 set -e
 
 
-# Make sure we're in the right folder.
-if ! [ -e bin/setup ] ; then
-    echo "Error: setup should be run from the project folder."
-    echo "Run as: bin/setup"
-    exit 1
+# Check if TRJ_HOME is not set.
+if [ -z $TRJ_HOME ]; then
+  # Notify user that TRJ_HOME is not set.
+  echo "Environment variable TRJ_HOME not found."
+  echo "Please configure the environment variable TRJ_HOME."
+  exit 1
 fi
+
+
+# Relocate into the TRJ_HOME just to be sure.
+cd $TRJ_HOME
 
 
 # Create basic project output directories.
@@ -41,13 +47,7 @@ fi
 
 
 # Compile java requirements.
-mvn compile
-
-
-# Set environment variable and notify user.
-export TRJ_HOME=$( pwd )
-echo "Place this in your ~/.bashrc file:"
-echo "export TRJ_HOME=$( pwd )"
+mvn clean compile package javadoc:javadoc
 
 
 exit 0
