Compile and install py reqs on the first run, if needed.

diff --git a/bin/scrape b/bin/scrape
--- a/bin/scrape
+++ b/bin/scrape
@@ -2,7 +2,8 @@
 
 
 # Check if TRJ_HOME is not set.
-if [ -z $TRJ_HOME ]; then
+if [ -z $TRJ_HOME ]
+then
   # Notify user that TRJ_HOME is not set.
   echo "Environment variable TRJ_HOME not found."
   echo "Please configure the environment variable TRJ_HOME."
@@ -13,6 +14,33 @@ fi
 # Relocate into the TRJ_HOME just to be sure.
 set -e
 cd $TRJ_HOME
+
+
+# Define python requirements installer.
+pyreq () {
+  if [ -f "requirements.txt" ]
+  then
+    pip install -r requirements.txt
+  else
+    echo "Python requirements file not found."
+    exit 1
+  fi
+}
+
+
+# Attempt to create virtual environment & install requirements.
+if [ ! -d "env" ]
+then
+  virtualenv env
+  source env/bin/activate
+  pyreq
+  touch .runonce
+elif [ ! -e ".runonce" ]
+then
+  source env/bin/activate
+  pyreq
+  touch .runonce
+fi
 
 
 # Ensure that the virtual environment is enabled.
