Moved build code back into appropriate scripts.

diff --git a/bin/scrape b/bin/scrape
--- a/bin/scrape
+++ b/bin/scrape
@@ -16,8 +16,31 @@ set -e
 cd $TRJ_HOME
 
 
-# Run build check.
-bin/util/build
+# Define python requirements installer.
+pyreq () {
+  if [ -f "requirements.txt" ]
+  then
+    pip install -r requirements.txt
+  else
+    echo "Python requirements file not found."
+    exit 1
+  fi
+}
+
+
+# Attempt to create virtual environment & install requirements.
+if [ ! -d "env" ]
+then
+  virtualenv env
+  source env/bin/activate
+  pyreq
+  touch .runonce
+elif [ ! -e ".runonce" ]
+then
+  source env/bin/activate
+  pyreq
+  touch .runonce
+fi
 
 
 # Ensure that the virtual environment is enabled.
